enum EventTypes {
  CHANGE_POSITION = 'CHANGE_POSITION',
  CALC_POSITION = 'CALC_POSITION',
  SET_POSITION = 'SET_POSITION',
  HANDLER_MOUSEDOWN_EVENT = 'HANDLER_MOUSEDOWN_EVENT',
  HANDLER_MOUSEMOVE_EVENT = 'HANDLER_MOUSEMOVE_EVENT',
  CALC_VALUE_NOTE_POSITION = 'CALC_VALUE_NOTE_POSITION',
  SET_VALUE_NOTE_POS = 'SET_VALUE_NOTE_POS',
  SET_BAR = 'SET_BAR',
}

export default EventTypes;
